apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hello_world # matches the workflow ID, will be used by orchestrator:workflow:run
  title: Hello World Workflow
  description: JSON based hello world workflow
  tags:
    - orchestrator
spec:
  owner: red-hat-developer-hub-authors
  system: red-hat-developer-hub
  type: service

  # matches workflow's dataInputSchema
  parameters:
    # keep on separate line
    

  steps:
    - id: runWorkflow
      name: Run workflow
      action: orchestrator:workflow:run
      input:
        parameters: ${{ parameters }}

  output:
    links:
      - title: Open workflow run
        url: ${{ steps.runWorkflow.output.instanceUrl }}
