apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: wait-or-error # matches the workflow ID, will be used by orchestrator:workflow:run
  title: Wait or Error
  description: Simple workflow to simulate waiting for callback or error
  tags:
    - orchestrator
spec:
  owner: red-hat-developer-hub-authors
  system: red-hat-developer-hub
  type: service

  # matches workflow's dataInputSchema
  parameters: 
    - $id: classpath:/schemas/wait-or-error__main-schema.json
      title: Data Input Schema
      $schema: http://json-schema.org/draft-07/schema#
      type: object
      properties:
        state:
          title: State
          description: State of the workflow
          enum:
            - Wait
            - Error
          default: Wait
    

  steps:
    - id: runWorkflow
      name: Run workflow
      action: orchestrator:workflow:run
      input:
        parameters: ${{ parameters }}

  output:
    links:
      - title: Open workflow run
        url: "${{ steps.runWorkflow.output.instanceUrl }}"
