apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: yamlgreet # matches the workflow ID, will be used by orchestrator:workflow:run
  title: Greeting workflow - gen
  description: YAML based greeting workflow
  tags:
    - orchestrator
spec:
  owner: red-hat-developer-hub-authors
  system: red-hat-developer-hub
  type: service

  # matches workflow's dataInputSchema
  parameters:
    # keep on separate line
    $id: classpath:/schemas/yamlgreet__main-schema.json
    title: Data Input Schema
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    properties:
      language:
        title: Language
        description: Language to greet
        type: string
        enum:
          - English
          - Spanish
        default: English
      name:
        title: Name
        description: Name of the person
        type: string
        default: John Doe
    required:
      - name
    

  steps:
    - id: runWorkflow
      name: Run workflow
      action: orchestrator:workflow:run
      input:
        # TODO: this needs to be escaped
        parameters: ${{ parameters }} 

  output:
    links:
      - title: Open workflow run
        # use: steps.runWorkflow.output.instanceUrl
        url: ${{ steps.runWorkflow.output.instanceUrl }}
